create_ip -name
blk_mem_gen
-vendor
xilinx.com
-library
ip
-version
8.4
-module_name
blk_mem_gen_1
-dir
{c:/Users/Eric
Tai/repo/vivado/MSPM/MSPM.srcs/sources_1/ip}
set_property
-dict
[list
CONFIG.Memory_Type
{Dual_Port_ROM}
CONFIG.Enable_B
{Use_ENB_Pin}
CONFIG.Register_PortB_Output_of_Memory_Primitives
{true}
CONFIG.Load_Init_File
{true}
CONFIG.Coe_File
{c:/Users/Eric
Tai/repo/vivado/MSPM/MSPM.srcs/sources_1/ip/example.coe}
CONFIG.Port_A_Write_Rate
{0}
CONFIG.Port_B_Clock
{100}
CONFIG.Port_B_Enable_Rate
{100}]
[get_ips
blk_mem_gen_1]
INFO:
[IP_Flow
19-3484]
Absolute
path
of
file
'c:/Users/Eric
Tai/repo/vivado/MSPM/MSPM.srcs/sources_1/ip/example.coe'
provided.
It
will
be
converted
relative
to
IP
Instance
files
'../example.coe'
generate_target
{instantiation_template}
[get_files
{{c:/Users/Eric
Tai/repo/vivado/MSPM/MSPM.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci}}]